### ISSUE TITLE
Add cost estimation

### ISSUE THREAD

**Issue by frol** [near/near-lake-framework#12]
https://github.com/near/near-lake/pull/25#discussion_r832103661:

> If I recall correctly, @telezhnaya estimated that assuming there are 8 shards (there are only 4 at the moment on mainnet) and block production is stable at 1 block per second, the cost of following each block and chunk in the network is roughly $10/month (paying for the read requests from S3).

It would be great to add real numbers to the README (e.g. we can setup a single node using private credentials and let it run for a week)

**Comment by khorolets** [comment]
$0.005 per 1000 requests

https://aws.amazon.com/s3/pricing/?nc1=h_ls

Assuming we produce a block every second, and we request a block every second. One full day it will be 86400 requests - it'll be $0,432 per day

So I guess it should be easy calculated to ~$13 per month

If you agree with my calculations I will create a special section in the README and by doing this I'll close this issue at that moment.

/cc @telezhnaya

**Comment by telezhnaya** [comment]
> One full day it will be 86400 requests

Nope. `* 5` because each block consists of 5 files now (1 general and 4 for each chunk)

But $13 is something close to what I got previous time (I've lost the computations, though)
How did you get $0,432 per day?

**Comment by khorolets** [comment]
> Nope. * 5 because

Ah, yeah, you're right

Then, 86400 blocks per day * 5 request for each / 1000 requests * $0.005 per 1k requests = $2.16 * 30 days = $64.8 

Not so brightly and kinda far away from $10 and $13.

**Comment by telezhnaya** [comment]
$0.0004 per 1k requests, reading is cheaper

**Comment by khorolets** [comment]
> $0.0004 per 1k requests, reading is cheaper

not really, `list` requests are charged for $0.005/1k

86400 blocks per day * 5 request for each / 1000 requests * $0.0004 per 1k requests = $0.173 * 30 days = $5.19

+ 86400 blocks per day / 1000 requests * $0.005 per 1k `list` requests = $0.432 * 30 days = $12.96

In total **$18.15 per month** this one is brighter :)

@telezhnaya agree with calculations?

**Comment by telezhnaya** [comment]
Yes! Looks accurate
Thank you
