### ISSUE TITLE
Block streaming interrupts when started from certain block height

### ISSUE THREAD

**Issue by okalenyk** [near/near-lake-framework#15]
Near lake framework stops printing out blocks for now particular reason working for about 10-20 seconds after launch. There are no errors or exceptions thrown - just stuck on some random block.

### Configuration:

**near-lake-raw-printer** at version [](https://github.com/near/near-lake-raw-printer/commit/3dc69b9e6fad70e7457b01c7b0a0bb3dbaef7ea1)(https://github.com/near/near-lake-raw-printer/commit/3dc69b9e6fad70e7457b01c7b0a0bb3dbaef7ea1)

**near-lake-framework dependency**: 

`near-lake-framework = { git = "https://github.com/near/near-lake-framework", rev = "fd207ed1bab4ba091f0c984cc2f1ec41b3feff07" }`

**LakeConfig**:

```
let config = LakeConfig {
    s3_bucket_name: "near-lake-data-testnet".to_string(),
    s3_region_name: "eu-central-1".to_string(),
    start_block_height: 82800242, // want to start from the freshest
};
```

Please let me know if I missed something or in case if you need more details.

**Comment by khorolets** [comment]
@okalenyk Please, could you try to use this hash `963fa0592a7d291ed180151427aa072777b8717e` and enable debug logs, so we can find out what's going on there together. I've checked on my end and didn't experience the issue you've described. Though I've found something that might have caused the issue.

**Comment by okalenyk** [comment]
Seems like the problem has disappeared in rev. 963fa0592a7d291ed180151427aa072777b8717e. Thanks a lot!
