### ISSUE TITLE
List object from the highest available object key on AWS S3 bucket

### ISSUE THREAD

**Issue by khorolets** [near/near-lake-framework#3]
According to the official API docs, we can get the list of AWS S3 bucket objects:
* either from the first (alphabetical order)
* or after the specified key (block height in our case)

I couldn't find a way to get the list of the objects in DESC order for instance. But the most crucial use case for NEAR Lake Framework is the possibility to get the stream of messages from the latest (final) record.

IDEAS we have to achieve this goal:

A proposal to let NEAR Lake itself is to create/update a metafile in the bucket it is connected to. While we haven't met any other needs, we can store the highest block height number we know so far. 
The con of this idea is that if we are running more than one NEAR Lake instance for the same network (e.g. one archival from the genesis filling the gaps and one regular closer to the tip of the network storing the up to date objects) we will create a race condition and each of the nodes will override the data saved from each other. Though, I believe we can read the file before updating and check if the value we are going to write is higher than the value already present in the metafile. In case of trying to store the lower value - skip the save, otherwise override the file. Although, we have a concern that we are talking about milliseconds for conditions to change and it might not play as well as expected.

We are open to other ideas.

/cc @frol 

**UPD**

We've decided to make it this way:

* Block height to start streaming from should be provided by the user
* if block height to start streaming from is missing the stream will start from the genesis block

**Comment by khorolets** [comment]
Another idea:

In the case of "latest" block height to start a stream from we can query the RPC to get the latest block height.

Props: it is possible
Cons: introduces a dependency of RPC we want to avoid

**Comment by khorolets** [comment]
DECISION made so far: 

We cannot satisfy every possible user with their use cases of the strategies from where to start the stream. We've decided that on the NEAR Lake Framework side we will require `start_block_height` to be provided and "force" users to program the way of identifying the block to start from on their own

**Comment by frol** [comment]
We may implement binary search to find the latest block height, but it is not worth the trouble now. Before 1.0 release we would need to make sure we have a way to extend the APIs in a non-breaking way.

**Comment by frol** [comment]
To find the most recent block we can just use binary search by the block height (start with [0; 1_000_000_000] range and try querying block with height 500_000_000, and so on)

**Comment by khorolets** [comment]
We've decided that this kind of feature should be implemented on the indexer side, not on the framework. The easiest way to do it is to use the [`near-jsonrpc-client`](https://github.com/near/near-jsonrpc-client-rs)

See [the tutorial about start options](https://near-indexers.io/tutorials/lake/lake-start-options#fromlatest) we've made to cover this on the docs site
