### ISSUE TITLE
Using `serde_json` before 1.0.75 and with feature `arbitrary_precision`

### ISSUE THREAD

**Issue by tifrel** [near/near-lake-framework#34]
When using `near-lake-framework` (reproducible with 0.2.0 and 0.4.0) together with the `serde_json` feature `arbitrary_precision` prior to version 1.0.75, block parsing fails:

```log
453:2022-05-30T11:14:22.840419Z DEBUG near_lake_framework: Failed to parse the 000088630666/shard_0.json. Retrying in 1s...
```

Version `near-lake-framework` v0.2.0 panics instead of the debug log. v0.4.0 enters an infinite loop with lots of fetches from S3. Consumers of `near-lake-framework` may either deactivate `arbitrary_precision` or upgrade `serde_json` to fix this.

[Link to minimum reproducible example](https://github.com/tifrel/near-lake-async-debug)

**Comment by frol** [comment]
Fixed in #35 and will be released as near-lake-framework 0.4.1 version #37
